changelog:
  exclude:
    authors:
      - dependabot
      - github-actions
    labels:
      - "changelog: none"

  categories:
    # Major level
    - title: Breaking Changes 🚨
      labels:
        - "[actions] changelog: breaking"

    # Minor level
    - title: New Features 🎉
      labels:
        - "[actions] changelog: add"

    - title: Updated ✨
      labels:
        - "[actions] changelog: update"

    # Patch level
    - title: Bug Fixes 🐛
      labels:
        - "[actions] changelog: fix"

    - title: Tweaked 🔧
      labels:
        - "[actions] changelog: tweak"

    - title: Documentation 📚
      labels:
        - "[actions] changelog: docs"
